name: Release Pipeline Labeler
description: Label issues as the progress through the release pipeline
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  appInsightsKey:
    description: Optional key to log to app insights. Defaults to the secret "TRIAGE_ACTIONS_APP_INSIGHTS"
    default: ${{ secrets.TRIAGE_ACTIONS_APP_INSIGHTS }}
  notYetReleasedLabel:
    description: Label for issues that should be included in the release pipeline action, but are not yet released.
    required: true
  insidersReleasedLabel:
    description: Label for issues that have been released to Insiders
    required: true
runs:
  using: 'node12'
  main: 'index.js'
