name: Author Verified
description: Allow issue authors to verify their own issues by pinging them when the fix goes into insiders
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  appInsightsKey:
    description: Optional key to log to app insights. Defaults to the secret "TRIAGE_ACTIONS_APP_INSIGHTS"
    default: ${{ secrets.TRIAGE_ACTIONS_APP_INSIGHTS }}
  requestVerificationComment:
    description: Comment to add whenn asking authors to verify the issue. ${commit} and ${author} will be substituted
    required: true
  pendingReleaseLabel:
    description: Label for Action to add for issue that authors can verify, but are not yet released
    required: true
  authorVerificationRequestedLabel:
    description: Label added by issue fixer to signal that the author can verify the issue
    required: true
runs:
  using: 'node12'
  main: 'index.js'
