name: "Trainer: Upload Models"
description: Upload models to blob storage
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  appInsightsKey:
    description: Optional key to log to app insights. Defaults to the secret "TRIAGE_ACTIONS_APP_INSIGHTS"
    default: ${{ secrets.TRIAGE_ACTIONS_APP_INSIGHTS }}
  blobContainerName:
    description: Name of Azure Storage container
    required: true
  blobStorageKey:
    description: Access string for blob storage account
    required: true
runs:
  using: 'node12'
  main: 'index.js'
