name: 'Regex Labeler'
description: Close issues that do or don't match particular Regex's
inputs:
  token:
    description: 'GitHub token with issue, comment, and label read/write permissions'
    default: ${{ github.token }}
  appInsightsKey:
    description: Optional key to log to app insights. Defaults to the secret "TRIAGE_ACTIONS_APP_INSIGHTS"
    default: ${{ secrets.TRIAGE_ACTIONS_APP_INSIGHTS }}
  mustMatch:
    description: If the issue body (excluding comments) does not match this regex, the action is performed
  mustNotMatch:
    description: If the issue body (excluding comments) matches regex, the action is performed
  comment:
    description: Comment to post to issues that don't fit the criteria
  label:
    description: Label to apply to isses that don't fit the criteria
runs:
  using: 'node12'
  main: 'index.js'
