name: Latest Release Monitor
description: Keep track of the latest releases of insiders and stable and trigger webhook events when they change
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions
    default: ${{ github.token }}
  appInsightsKey:
    description: Optional key to log to app insights. Defaults to the secret "TRIAGE_ACTIONS_APP_INSIGHTS"
    default: ${{ secrets.TRIAGE_ACTIONS_APP_INSIGHTS }}
  storageKey:
    description: Azure blob storage connection string
    required: true
runs:
  using: 'node12'
  main: 'index.js'
