name: Copycat
description: Copy all new issues to a different repo
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions to both repos
    default: ${{ github.token }}
  appInsightsKey:
    description: Optional key to log to app insights. Defaults to the secret "TRIAGE_ACTIONS_APP_INSIGHTS"
    default: ${{ secrets.TRIAGE_ACTIONS_APP_INSIGHTS }}
  owner:
    description: account/organization that owns the destination repo (the microsoft part of microsoft/vscode)
    required: true
  repo:
    description: name of the destination repo (the vscode part of microsoft/vscode)
    required: true
runs:
  using: 'node12'
  main: 'index.js'
